class Config:
    #Generate this key with os.urandom(24).hex()
    SECRET_KEY = "XXXXXXXXXXXXXXXXXXXXXXXXXXX"
    SQLALCHEMY_DATABASE_URI = "XXXXXXXXXXXXXXXXXXXXXXXXXXX"
    SQLALCHEMY_TRACK_MODIFICATIONS = False