"""Added Connections to App Settings

Revision ID: 066a10501ba2
Revises: 8295576eb028
Create Date: 2023-06-26 17:24:34.877929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '066a10501ba2'
down_revision = '8295576eb028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sonarr_connection')
    op.drop_table('radarr_connection')
    op.drop_table('ombi_connection')
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('radarrHost', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('radarrPort', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('radarrPpiKey', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sonarrHost', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sonarrPort', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sonarrApiKey', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ombiHost', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ombiPort', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ombiApiKey', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('ombiApiKey')
        batch_op.drop_column('ombiPort')
        batch_op.drop_column('ombiHost')
        batch_op.drop_column('sonarrApiKey')
        batch_op.drop_column('sonarrPort')
        batch_op.drop_column('sonarrHost')
        batch_op.drop_column('radarrPpiKey')
        batch_op.drop_column('radarrPort')
        batch_op.drop_column('radarrHost')

    op.create_table('ombi_connection',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('host', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('port', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('apiKey', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('radarr_connection',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('host', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('port', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('apiKey', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sonarr_connection',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('host', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('port', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('apiKey', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
