"""First commit

Revision ID: 07601611e932
Revises: 
Create Date: 2023-06-30 14:41:29.998413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07601611e932'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delayNumber', sa.Integer(), nullable=True),
    sa.Column('delayUnit', sa.String(length=50), nullable=True),
    sa.Column('radarrHost', sa.String(length=100), nullable=True),
    sa.Column('radarrPort', sa.Integer(), nullable=True),
    sa.Column('radarrApiKey', sa.String(length=100), nullable=True),
    sa.Column('sonarrHost', sa.String(length=100), nullable=True),
    sa.Column('sonarrPort', sa.Integer(), nullable=True),
    sa.Column('sonarrApiKey', sa.String(length=100), nullable=True),
    sa.Column('ombiHost', sa.String(length=100), nullable=True),
    sa.Column('ombiPort', sa.Integer(), nullable=True),
    sa.Column('ombiApiKey', sa.String(length=100), nullable=True),
    sa.Column('lastMediaImport', sa.DateTime(), nullable=True),
    sa.Column('plexClientID', sa.String(length=100), nullable=True),
    sa.Column('appName', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('plexid', sa.Integer(), nullable=True),
    sa.Column('alias', sa.String(length=100), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('plexid')
    )
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('releaseDate', sa.DateTime(), nullable=True),
    sa.Column('theMovieDbID', sa.Integer(), nullable=True),
    sa.Column('theMovieDbURL', sa.String(length=100), nullable=True),
    sa.Column('ombiID', sa.Integer(), nullable=True),
    sa.Column('radarrID', sa.Integer(), nullable=True),
    sa.Column('totalSize', sa.Integer(), nullable=True),
    sa.Column('abandonnedDate', sa.DateTime(), nullable=True),
    sa.Column('deleteDate', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tv_show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('tvDbID', sa.Integer(), nullable=True),
    sa.Column('tvDbURL', sa.String(length=100), nullable=True),
    sa.Column('ombiID', sa.Integer(), nullable=True),
    sa.Column('sonarrID', sa.Integer(), nullable=True),
    sa.Column('totalSize', sa.Integer(), nullable=True),
    sa.Column('abandonnedDate', sa.DateTime(), nullable=True),
    sa.Column('deleteDate', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tv_show')
    op.drop_table('movie')
    op.drop_table('user')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
