"""Correction

Revision ID: 0ad066568df4
Revises: 388d315eb4e3
Create Date: 2023-06-27 18:38:23.140504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ad066568df4'
down_revision = '388d315eb4e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column('releaseDate',
               existing_type=mysql.INTEGER(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column('releaseDate',
               existing_type=sa.DateTime(),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
