"""Updated for password reset

Revision ID: 31160afc9de7
Revises: f5f64ad96c8e
Create Date: 2023-06-26 10:16:51.706013

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '31160afc9de7'
down_revision = 'f5f64ad96c8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('lastlogin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastlogin', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
