"""Removed system user attribute

Revision ID: 34c693048216
Revises: 3a893d4f81ae
Create Date: 2023-11-11 22:51:36.444680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34c693048216'
down_revision = '3a893d4f81ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('system_user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_user', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
