"""Changing App Settings

Revision ID: 36a2ade59cd4
Revises: eb2772ed22e8
Create Date: 2023-06-30 03:51:52.550389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36a2ade59cd4'
down_revision = 'eb2772ed22e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plexClientID', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('appName', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('appName')
        batch_op.drop_column('plexClientID')

    # ### end Alembic commands ###
