"""Bigger string for poster_url

Revision ID: 466efa028ac9
Revises: 57ac639a62db
Create Date: 2023-08-01 21:29:33.434465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '466efa028ac9'
down_revision = '57ac639a62db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('poster_url',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('poster_url',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
