"""Added abandonned date

Revision ID: 54c15959bc95
Revises: 8b24763d033c
Create Date: 2023-07-28 08:39:59.816636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54c15959bc95'
down_revision = '8b24763d033c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abandonned_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_column('abandonned_date')

    # ### end Alembic commands ###
