"""Remove last user

Revision ID: 57ae09624137
Revises: 9097510753aa
Create Date: 2023-11-06 13:37:02.384796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57ae09624137'
down_revision = '9097510753aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_constraint('fk_media_last_user_id_user', type_='foreignkey')
        batch_op.drop_column('last_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_media_last_user_id_user', 'user', ['last_user_id'], ['id'])

    # ### end Alembic commands ###
