"""Corrected type

Revision ID: 739141de548b
Revises: 066a10501ba2
Create Date: 2023-06-26 17:26:12.076037

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '739141de548b'
down_revision = '066a10501ba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('radarrApiKey', sa.String(length=100), nullable=True))
        batch_op.drop_column('radarrPpiKey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('radarrPpiKey', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('radarrApiKey')

    # ### end Alembic commands ###
