"""Added Safe Mode

Revision ID: 8b24763d033c
Revises: a7e57ce4c0d6
Create Date: 2023-07-27 18:42:02.040421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b24763d033c'
down_revision = 'a7e57ce4c0d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('safe_mode', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('safe_mode')

    # ### end Alembic commands ###
