"""Abandonned typo fix

Revision ID: 9097510753aa
Revises: ebfcf75c0eec
Create Date: 2023-11-05 14:56:07.045911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9097510753aa'
down_revision = 'ebfcf75c0eec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column(column_name='abandonned_date', new_column_name='abandoned_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column(column_name='abandoned_date', new_column_name='abandonned_date')

    # ### end Alembic commands ###
