"""Initial

Revision ID: a7e57ce4c0d6
Revises: 
Create Date: 2023-07-27 08:35:08.839129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7e57ce4c0d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expiry_time_number', sa.Integer(), nullable=True),
    sa.Column('expiry_time_unit', sa.String(length=50), nullable=True),
    sa.Column('next_delete', sa.DateTime(), nullable=True),
    sa.Column('deletion_time_number', sa.Integer(), nullable=True),
    sa.Column('deletion_time_unit', sa.String(length=50), nullable=True),
    sa.Column('last_media_import', sa.DateTime(), nullable=True),
    sa.Column('radarr_host', sa.String(length=100), nullable=True),
    sa.Column('radarr_port', sa.Integer(), nullable=True),
    sa.Column('radarr_api_key', sa.String(length=100), nullable=True),
    sa.Column('sonarr_host', sa.String(length=100), nullable=True),
    sa.Column('sonarr_port', sa.Integer(), nullable=True),
    sa.Column('sonarr_api_key', sa.String(length=100), nullable=True),
    sa.Column('ombi_host', sa.String(length=100), nullable=True),
    sa.Column('ombi_port', sa.Integer(), nullable=True),
    sa.Column('ombi_api_key', sa.String(length=100), nullable=True),
    sa.Column('plex_client_id', sa.String(length=100), nullable=True),
    sa.Column('app_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.Unicode(length=191), nullable=False),
    sa.Column('next_run_time', sa.Float(precision=25), nullable=True),
    sa.Column('job_state', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apscheduler_jobs_next_run_time'), ['next_run_time'], unique=False)

    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('ombi_id', sa.Integer(), nullable=False),
    sa.Column('total_size', sa.BigInteger(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('deletion_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('alias', sa.String(length=100), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('TMDB_id', sa.Integer(), nullable=False),
    sa.Column('TMDB_url', sa.String(length=100), nullable=True),
    sa.Column('radarr_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('TMDB_id')
    )
    op.create_table('pick',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pick_method', sa.String(length=100), nullable=True),
    sa.Column('pick_date', sa.DateTime(), nullable=True),
    sa.Column('media_type', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tv_show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theTVDB_id', sa.Integer(), nullable=False),
    sa.Column('theTVDB_url', sa.String(length=100), nullable=True),
    sa.Column('sonarr_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('theTVDB_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tv_show')
    op.drop_table('pick')
    op.drop_table('movie')
    op.drop_table('user')
    op.drop_table('media')
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apscheduler_jobs_next_run_time'))

    op.drop_table('apscheduler_jobs')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
