"""Initial commit

Revision ID: bd2c2d298be4
Revises: 
Create Date: 2023-07-15 13:50:28.520405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd2c2d298be4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expiryTimeNumber', sa.Integer(), nullable=True),
    sa.Column('expiryTimeUnit', sa.String(length=50), nullable=True),
    sa.Column('nextDelete', sa.DateTime(), nullable=True),
    sa.Column('deletionTimeNumber', sa.Integer(), nullable=True),
    sa.Column('deletionTimeUnit', sa.String(length=50), nullable=True),
    sa.Column('lastMediaImport', sa.DateTime(), nullable=True),
    sa.Column('importInterval', sa.DateTime(), nullable=True),
    sa.Column('nextImportDate', sa.DateTime(), nullable=True),
    sa.Column('radarrHost', sa.String(length=100), nullable=True),
    sa.Column('radarrPort', sa.Integer(), nullable=True),
    sa.Column('radarrApiKey', sa.String(length=100), nullable=True),
    sa.Column('sonarrHost', sa.String(length=100), nullable=True),
    sa.Column('sonarrPort', sa.Integer(), nullable=True),
    sa.Column('sonarrApiKey', sa.String(length=100), nullable=True),
    sa.Column('ombiHost', sa.String(length=100), nullable=True),
    sa.Column('ombiPort', sa.Integer(), nullable=True),
    sa.Column('ombiApiKey', sa.String(length=100), nullable=True),
    sa.Column('plexClientID', sa.String(length=100), nullable=True),
    sa.Column('appName', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('ombiID', sa.Integer(), nullable=False),
    sa.Column('totalSize', sa.Integer(), nullable=True),
    sa.Column('expiryDate', sa.DateTime(), nullable=True),
    sa.Column('deletionDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ombiID')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('alias', sa.String(length=100), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('releaseDate', sa.DateTime(), nullable=False),
    sa.Column('theMovieDbID', sa.Integer(), nullable=False),
    sa.Column('theMovieDbURL', sa.String(length=100), nullable=True),
    sa.Column('radarrID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('radarrID'),
    sa.UniqueConstraint('theMovieDbID')
    )
    op.create_table('pick',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pick_method', sa.String(length=100), nullable=True),
    sa.Column('pick_date', sa.DateTime(), nullable=True),
    sa.Column('media_type', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tv_show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tvDbID', sa.Integer(), nullable=False),
    sa.Column('tvDbURL', sa.String(length=100), nullable=True),
    sa.Column('sonarrID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tvDbID')
    )
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_apscheduler_jobs_next_run_time')

    op.drop_table('apscheduler_jobs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', sa.FLOAT(), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_apscheduler_jobs_next_run_time', ['next_run_time'], unique=False)

    op.drop_table('tv_show')
    op.drop_table('pick')
    op.drop_table('movie')
    op.drop_table('user')
    op.drop_table('media')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
