"""Initial commit

Revision ID: d2485c4df09d
Revises: 
Create Date: 2023-07-04 20:19:05.220799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2485c4df09d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expiryTimeNumber', sa.Integer(), nullable=True),
    sa.Column('expiryTimeUnit', sa.String(length=50), nullable=True),
    sa.Column('nextDelete', sa.DateTime(), nullable=True),
    sa.Column('deletionInterval', sa.DateTime(), nullable=True),
    sa.Column('lastMediaImport', sa.DateTime(), nullable=True),
    sa.Column('importInterval', sa.DateTime(), nullable=True),
    sa.Column('nextImportDate', sa.DateTime(), nullable=True),
    sa.Column('radarrHost', sa.String(length=100), nullable=True),
    sa.Column('radarrPort', sa.Integer(), nullable=True),
    sa.Column('radarrApiKey', sa.String(length=100), nullable=True),
    sa.Column('sonarrHost', sa.String(length=100), nullable=True),
    sa.Column('sonarrPort', sa.Integer(), nullable=True),
    sa.Column('sonarrApiKey', sa.String(length=100), nullable=True),
    sa.Column('ombiHost', sa.String(length=100), nullable=True),
    sa.Column('ombiPort', sa.Integer(), nullable=True),
    sa.Column('ombiApiKey', sa.String(length=100), nullable=True),
    sa.Column('plexClientID', sa.String(length=100), nullable=True),
    sa.Column('appName', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('releaseDate', sa.DateTime(), nullable=False),
    sa.Column('theMovieDbID', sa.Integer(), nullable=False),
    sa.Column('theMovieDbURL', sa.String(length=100), nullable=True),
    sa.Column('ombiID', sa.Integer(), nullable=False),
    sa.Column('radarrID', sa.Integer(), nullable=True),
    sa.Column('totalSize', sa.Integer(), nullable=True),
    sa.Column('expiryDate', sa.DateTime(), nullable=True),
    sa.Column('deletionDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ombiID'),
    sa.UniqueConstraint('radarrID'),
    sa.UniqueConstraint('theMovieDbID')
    )
    op.create_table('tv_show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('tvDbID', sa.Integer(), nullable=True),
    sa.Column('tvDbURL', sa.String(length=100), nullable=True),
    sa.Column('ombiID', sa.Integer(), nullable=True),
    sa.Column('sonarrID', sa.Integer(), nullable=True),
    sa.Column('totalSize', sa.Integer(), nullable=True),
    sa.Column('expiryDate', sa.DateTime(), nullable=True),
    sa.Column('deletionDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('alias', sa.String(length=100), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pick',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('pick_method', sa.String(length=100), nullable=True),
    sa.Column('pick_date', sa.DateTime(), nullable=True),
    sa.Column('picker_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['picker_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie_pick',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['pick.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tv_show_pick',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tvShow_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['pick.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['tvShow_id'], ['tv_show.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tv_show_pick')
    op.drop_table('movie_pick')
    op.drop_table('pick')
    op.drop_table('user')
    op.drop_table('tv_show')
    op.drop_table('movie')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
