"""Adding pick type

Revision ID: d6bd5d900e35
Revises: 34c693048216
Create Date: 2023-11-16 15:43:16.933491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6bd5d900e35'
down_revision = '34c693048216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pick_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pick_type')),
    sa.UniqueConstraint('name', name=op.f('uq_pick_type_name'))
    )
    with op.batch_alter_table('pick', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pick_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_pick_pick_type_id_pick_type'), 'pick_type', ['pick_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pick', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_pick_pick_type_id_pick_type'), type_='foreignkey')
        batch_op.drop_column('pick_type_id')

    op.drop_table('pick_type')
    # ### end Alembic commands ###
