"""Added storage to user

Revision ID: ebfcf75c0eec
Revises: 98f7b07ead5c
Create Date: 2023-09-22 09:51:14.076203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebfcf75c0eec'
down_revision = '98f7b07ead5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movie_storage_usage', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('show_storage_usage', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('show_storage_usage')
        batch_op.drop_column('movie_storage_usage')

    # ### end Alembic commands ###
